name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install packages
      run: sudo apt install cmake libboost-all-dev ninja-build
    - name: pull submodules
      run: git submodule update --init --recursive
    - name: cmake
      run: cmake -DCMAKE_BUILD_TYPE=Debug -GNinja .
    - name: build
      run: ninja
    - name: run tests
      run: ./run_rs_tests
